# Generated by Django 4.2.1 on 2023-07-26 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schooluser',
            options={'ordering': ['first_name', 'last_name']},
        ),
    ]
