# Generated by Django 4.2.1 on 2023-08-01 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0002_alter_schooluser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schooluser',
            options={'ordering': ['first_name', 'last_name', 'date_joined']},
        ),
    ]
