# Generated by Django 4.2.1 on 2023-08-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0004_alter_schooluser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schooluser',
            options={'ordering': ['pk', 'first_name', 'last_name']},
        ),
        migrations.AlterField(
            model_name='schooluser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.'),
        ),
    ]
