# Generated by Django 4.2.1 on 2023-08-07 15:03

from django.db import migrations, models
import eSchoolManager.accounts_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0005_alter_schooluser_options_alter_schooluser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooluser',
            name='first_name',
            field=models.CharField(max_length=40, validators=[eSchoolManager.accounts_app.validators.NoNumInName()]),
        ),
        migrations.AlterField(
            model_name='schooluser',
            name='last_name',
            field=models.CharField(max_length=40, validators=[eSchoolManager.accounts_app.validators.NoNumInName()]),
        ),
    ]
