# Generated by Django 4.2.1 on 2023-08-07 15:03

from django.db import migrations, models
import eSchoolManager.principal_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('principal_app', '0002_alter_principalprofile_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principalprofile',
            name='address',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='principalprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[eSchoolManager.principal_app.validators.MaxYearRange()]),
        ),
        migrations.AlterField(
            model_name='principalprofile',
            name='phone',
            field=models.CharField(blank=True, null=True, validators=[eSchoolManager.principal_app.validators.CheckIfValidPhone(), eSchoolManager.principal_app.validators.NoCharInNumber()]),
        ),
    ]
