# Generated by Django 4.2.1 on 2023-08-11 15:35

from django.db import migrations, models
import eSchoolManager.principal_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('principal_app', '0003_alter_principalprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principalprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[eSchoolManager.principal_app.validators.MaxYearRange(100)]),
        ),
    ]
