# Generated by Django 4.2.1 on 2023-08-09 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0002_alter_subjectsmodel_subject_name'),
        ('teachers_app', '0006_alter_teacherprofile_date_of_birth'),
        ('classes_app', '0003_teacherclass_subject'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacherclass',
            unique_together={('teacher', 'school_class', 'subject')},
        ),
    ]
