# Generated by Django 4.2.1 on 2023-07-26 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddGradeToStudentModel',
        ),
    ]
