# Generated by Django 4.2.1 on 2023-07-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_app', '0002_delete_addgradetostudentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='image_url',
            field=models.URLField(blank=True, default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRb7b5Uk6-fslFsGiTi_zqcNqdn9QqIC8AMxw&usqp=CAU', null=True),
        ),
    ]
