# Generated by Django 4.2.1 on 2023-07-28 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_app', '0003_alter_teacherprofile_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherprofile',
            options={'ordering': ['user']},
        ),
    ]
