# Generated by Django 4.2.1 on 2023-08-07 15:03

from django.db import migrations, models
import eSchoolManager.teachers_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_app', '0004_alter_teacherprofile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='address',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[eSchoolManager.teachers_app.validators.MaxYearRange()]),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='phone',
            field=models.CharField(blank=True, null=True, validators=[eSchoolManager.teachers_app.validators.CheckIfValidPhone(), eSchoolManager.teachers_app.validators.NoCharInNumber()]),
        ),
    ]
