# Generated by Django 4.2.1 on 2023-08-09 11:56

from django.db import migrations, models
import eSchoolManager.teachers_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_app', '0005_alter_teacherprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[eSchoolManager.teachers_app.validators.MaxYearRange(100)]),
        ),
    ]
