# Generated by Django 4.2.1 on 2023-07-26 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0001_initial'),
        ('students_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddGradeToStudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_app.grademodel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_app.studentprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_app.subjectsmodel')),
            ],
            options={
                'ordering': ['student_id', 'subject_id'],
            },
        ),
    ]
