# Generated by Django 4.2.1 on 2023-07-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0002_addgradetostudentmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'ordering': ['user']},
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='image_url',
            field=models.URLField(blank=True, default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRb7b5Uk6-fslFsGiTi_zqcNqdn9QqIC8AMxw&usqp=CAU', null=True),
        ),
    ]
