# Generated by Django 4.2.1 on 2023-07-31 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0003_alter_studentprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addgradetostudentmodel',
            options={},
        ),
    ]
