# Generated by Django 4.2.1 on 2023-08-07 13:20

from django.db import migrations, models
import eSchoolManager.students_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0004_alter_addgradetostudentmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='address',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(blank=True, null=True, validators=[eSchoolManager.students_app.validators.CheckIfValidPhone(), eSchoolManager.students_app.validators.NoCharInNumber()]),
        ),
    ]
