# Generated by Django 4.2.1 on 2023-08-11 15:35

from django.db import migrations, models
import eSchoolManager.students_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0006_alter_studentprofile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[eSchoolManager.students_app.validators.MaxYearRange(100)]),
        ),
    ]
